// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: node.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion   string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Os             string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	HaproxyVersion string                 `protobuf:"bytes,3,opt,name=haproxy_version,json=haproxyVersion,proto3" json:"haproxy_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HeartbeatRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HeartbeatRequest) GetHaproxyVersion() string {
	if x != nil {
		return x.HaproxyVersion
	}
	return ""
}

type HeartbeatReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConfigRevision uint64                 `protobuf:"varint,1,opt,name=config_revision,json=configRevision,proto3" json:"config_revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatReply) Reset() {
	*x = HeartbeatReply{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReply) ProtoMessage() {}

func (x *HeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReply.ProtoReflect.Descriptor instead.
func (*HeartbeatReply) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatReply) GetConfigRevision() uint64 {
	if x != nil {
		return x.ConfigRevision
	}
	return 0
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

type SyncReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConfigRevision uint64                 `protobuf:"varint,1,opt,name=config_revision,json=configRevision,proto3" json:"config_revision,omitempty"`
	AcmeEmail      string                 `protobuf:"bytes,2,opt,name=acme_email,json=acmeEmail,proto3" json:"acme_email,omitempty"`
	Sites          []*SiteSpec            `protobuf:"bytes,3,rep,name=sites,proto3" json:"sites,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncReply) Reset() {
	*x = SyncReply{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncReply) ProtoMessage() {}

func (x *SyncReply) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncReply.ProtoReflect.Descriptor instead.
func (*SyncReply) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

func (x *SyncReply) GetConfigRevision() uint64 {
	if x != nil {
		return x.ConfigRevision
	}
	return 0
}

func (x *SyncReply) GetAcmeEmail() string {
	if x != nil {
		return x.AcmeEmail
	}
	return ""
}

func (x *SyncReply) GetSites() []*SiteSpec {
	if x != nil {
		return x.Sites
	}
	return nil
}

type SiteSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       string                 `protobuf:"bytes,1,opt,name=domains,proto3" json:"domains,omitempty"`                         // comma-separated, first is the primary/cert name
	Upstream      string                 `protobuf:"bytes,2,opt,name=upstream,proto3" json:"upstream,omitempty"`                       // host:port
	HostMode      string                 `protobuf:"bytes,3,opt,name=host_mode,json=hostMode,proto3" json:"host_mode,omitempty"`       // "upstream" | "keep" | "custom"
	HostHeader    string                 `protobuf:"bytes,4,opt,name=host_header,json=hostHeader,proto3" json:"host_header,omitempty"` // used when host_mode == "custom"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteSpec) Reset() {
	*x = SiteSpec{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteSpec) ProtoMessage() {}

func (x *SiteSpec) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteSpec.ProtoReflect.Descriptor instead.
func (*SiteSpec) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

func (x *SiteSpec) GetDomains() string {
	if x != nil {
		return x.Domains
	}
	return ""
}

func (x *SiteSpec) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *SiteSpec) GetHostMode() string {
	if x != nil {
		return x.HostMode
	}
	return ""
}

func (x *SiteSpec) GetHostHeader() string {
	if x != nil {
		return x.HostHeader
	}
	return ""
}

type StatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HaproxyRunning bool                   `protobuf:"varint,1,opt,name=haproxy_running,json=haproxyRunning,proto3" json:"haproxy_running,omitempty"`
	ConfigOk       bool                   `protobuf:"varint,2,opt,name=config_ok,json=configOk,proto3" json:"config_ok,omitempty"`
	ConfigErr      string                 `protobuf:"bytes,3,opt,name=config_err,json=configErr,proto3" json:"config_err,omitempty"`
	Certs          []*CertStatus          `protobuf:"bytes,4,rep,name=certs,proto3" json:"certs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{5}
}

func (x *StatusRequest) GetHaproxyRunning() bool {
	if x != nil {
		return x.HaproxyRunning
	}
	return false
}

func (x *StatusRequest) GetConfigOk() bool {
	if x != nil {
		return x.ConfigOk
	}
	return false
}

func (x *StatusRequest) GetConfigErr() string {
	if x != nil {
		return x.ConfigErr
	}
	return ""
}

func (x *StatusRequest) GetCerts() []*CertStatus {
	if x != nil {
		return x.Certs
	}
	return nil
}

type CertStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	NotAfterUnix  int64                  `protobuf:"varint,3,opt,name=not_after_unix,json=notAfterUnix,proto3" json:"not_after_unix,omitempty"`
	DaysLeft      int32                  `protobuf:"varint,4,opt,name=days_left,json=daysLeft,proto3" json:"days_left,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertStatus) Reset() {
	*x = CertStatus{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertStatus) ProtoMessage() {}

func (x *CertStatus) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertStatus.ProtoReflect.Descriptor instead.
func (*CertStatus) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{6}
}

func (x *CertStatus) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CertStatus) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CertStatus) GetNotAfterUnix() int64 {
	if x != nil {
		return x.NotAfterUnix
	}
	return 0
}

func (x *CertStatus) GetDaysLeft() int32 {
	if x != nil {
		return x.DaysLeft
	}
	return 0
}

type StatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{7}
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\n" +
	"hpxnode.v1\"p\n" +
	"\x10HeartbeatRequest\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12'\n" +
	"\x0fhaproxy_version\x18\x03 \x01(\tR\x0ehaproxyVersion\"9\n" +
	"\x0eHeartbeatReply\x12'\n" +
	"\x0fconfig_revision\x18\x01 \x01(\x04R\x0econfigRevision\"\r\n" +
	"\vSyncRequest\"\x7f\n" +
	"\tSyncReply\x12'\n" +
	"\x0fconfig_revision\x18\x01 \x01(\x04R\x0econfigRevision\x12\x1d\n" +
	"\n" +
	"acme_email\x18\x02 \x01(\tR\tacmeEmail\x12*\n" +
	"\x05sites\x18\x03 \x03(\v2\x14.hpxnode.v1.SiteSpecR\x05sites\"~\n" +
	"\bSiteSpec\x12\x18\n" +
	"\adomains\x18\x01 \x01(\tR\adomains\x12\x1a\n" +
	"\bupstream\x18\x02 \x01(\tR\bupstream\x12\x1b\n" +
	"\thost_mode\x18\x03 \x01(\tR\bhostMode\x12\x1f\n" +
	"\vhost_header\x18\x04 \x01(\tR\n" +
	"hostHeader\"\xa2\x01\n" +
	"\rStatusRequest\x12'\n" +
	"\x0fhaproxy_running\x18\x01 \x01(\bR\x0ehaproxyRunning\x12\x1b\n" +
	"\tconfig_ok\x18\x02 \x01(\bR\bconfigOk\x12\x1d\n" +
	"\n" +
	"config_err\x18\x03 \x01(\tR\tconfigErr\x12,\n" +
	"\x05certs\x18\x04 \x03(\v2\x16.hpxnode.v1.CertStatusR\x05certs\"\x7f\n" +
	"\n" +
	"CertStatus\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12$\n" +
	"\x0enot_after_unix\x18\x03 \x01(\x03R\fnotAfterUnix\x12\x1b\n" +
	"\tdays_left\x18\x04 \x01(\x05R\bdaysLeft\"\r\n" +
	"\vStatusReply2\xd0\x01\n" +
	"\vNodeService\x12E\n" +
	"\tHeartbeat\x12\x1c.hpxnode.v1.HeartbeatRequest\x1a\x1a.hpxnode.v1.HeartbeatReply\x126\n" +
	"\x04Sync\x12\x17.hpxnode.v1.SyncRequest\x1a\x15.hpxnode.v1.SyncReply\x12B\n" +
	"\fReportStatus\x12\x19.hpxnode.v1.StatusRequest\x1a\x17.hpxnode.v1.StatusReplyB\"Z github.com/nexpool/hpxnode/pb;pbb\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_node_proto_goTypes = []any{
	(*HeartbeatRequest)(nil), // 0: hpxnode.v1.HeartbeatRequest
	(*HeartbeatReply)(nil),   // 1: hpxnode.v1.HeartbeatReply
	(*SyncRequest)(nil),      // 2: hpxnode.v1.SyncRequest
	(*SyncReply)(nil),        // 3: hpxnode.v1.SyncReply
	(*SiteSpec)(nil),         // 4: hpxnode.v1.SiteSpec
	(*StatusRequest)(nil),    // 5: hpxnode.v1.StatusRequest
	(*CertStatus)(nil),       // 6: hpxnode.v1.CertStatus
	(*StatusReply)(nil),      // 7: hpxnode.v1.StatusReply
}
var file_node_proto_depIdxs = []int32{
	4, // 0: hpxnode.v1.SyncReply.sites:type_name -> hpxnode.v1.SiteSpec
	6, // 1: hpxnode.v1.StatusRequest.certs:type_name -> hpxnode.v1.CertStatus
	0, // 2: hpxnode.v1.NodeService.Heartbeat:input_type -> hpxnode.v1.HeartbeatRequest
	2, // 3: hpxnode.v1.NodeService.Sync:input_type -> hpxnode.v1.SyncRequest
	5, // 4: hpxnode.v1.NodeService.ReportStatus:input_type -> hpxnode.v1.StatusRequest
	1, // 5: hpxnode.v1.NodeService.Heartbeat:output_type -> hpxnode.v1.HeartbeatReply
	3, // 6: hpxnode.v1.NodeService.Sync:output_type -> hpxnode.v1.SyncReply
	7, // 7: hpxnode.v1.NodeService.ReportStatus:output_type -> hpxnode.v1.StatusReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
